### ISSUE TITLE
Write up KLD and p-value methodology

### ISSUE THREAD

**Issue by korenmiklos** [ceumicrodata/economic-diplomacy#38]

**Comment by korenmiklos** [comment]
I think it's done, @zaveczgergo, please review on overleaf.

**Comment by zaveczgergo** [comment]
@korenmiklos 
Seems good to me. There was on unfinished sentence for KLD on page 3 (probably you are still working on that), and still on page 3 I was a bit unsure how there are 10^3 * 9 possibilities for distributing shipments across product codes (but I just might misunderstand that part).
I do not know how specific we should be at this point, but in case of GDELT: 1, for intent we only use intent to cooperate, 2, for visits material cooperation is also used in the composite index (which is the sum of three variables).
