### ISSUE TITLE
Add EU intent and visits to the analysis data

### ISSUE THREAD

**Issue by korenmiklos** [ceumicrodata/economic-diplomacy#44]

**Comment by korenmiklos** [comment]
We could include this as control in the regressions without fixed effects.

**Comment by zaveczgergo** [comment]
By the EU intent and visits do you mean a sum of intent and visits by all EU countries with the given pair in the given year? @korenmiklos

**Comment by korenmiklos** [comment]
This can also work, but we have specific GDELT data about EU agencies (`ECO` or some other code). Is this in the bead?

**Comment by zaveczgergo** [comment]
Oh, I got it. Then I just keep what I have produced, and create new variables for these. `EUR` appears in the country codes, now I can see them.
