### ISSUE TITLE
Cut GDELT histogram at 300

### ISSUE THREAD

**Issue by korenmiklos** [ceumicrodata/economic-diplomacy#53]
`if intent <= 300 & visits <= 300` 

Make note of this in figure notes.

**Comment by zaveczgergo** [comment]
For some reason it did not let me to push the new graph to overleaf. And now it wants to merge branches if I try again. Is it because overleaf is also opened on your computer? @korenmiklos

**Comment by zaveczgergo** [comment]
Solved it, pushed the graphs.
